<footer class="footer_container">
    <a href="https://discord.com"><img class="footer_logo" src="images/discord.svg" alt="Our Discord server"></a>
    <a href="https://jonahclydeswin.atlassian.net/jira/software/projects/SCRUM/boards/1/timeline"><img class="footer_logo" src="images/jira.svg" alt="Our Jira board"></a>
    <a href="mailto:info@melonball.com"> <img class="footer_logo" src="images/email.svg" alt="Email us"></a>
    <a href="https://github.com/ThankYouBonsai/Applied_Web_Project_G01.git"><img class="footer_logo" src="images/github-mark.png" alt="Github Repository"> </a>
</footer>