<header>
    <!-- Header -->
    <!-- Hamburger Menu -->
    <label class="hamburger_menu" for="hamburger">
    <span class="hidden_text">hidden</span>
    <input type="checkbox" name="hamburger" id="hamburger">
    </label>
    <div class="sidebar">
    <nav>
        <ul>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
        </ul>
    </nav>
    </div>
    <!-- Normal Header -->
    <div class="header_container">
    <div class="nav_container">
        <nav>
        <ul>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
        </ul>
        </nav>
    </div>            
    <div class="logo_container">
        <a href="index.php"><img id="logo" src="images/Logo_Black.svg" 
        alt="MELONBALL logo with white curved segments and a bold red stripe, outlined in black" title="MELONBALL Logo">
        </a>
        <p>MELON<strong>BALL</strong></p>
    </div>
    <div class="right_spacer"></div>
    </div>
    <!-- End of Header -->
</header>