<!--
    - Company details (logo, name, slogan, description, image), 
    - common navigation menu, 
    - footer with Jira & GitHub repository link, 
    - email link (info@companyname.com).

    - Must display a background graphic using CSS.

    JIRA Link: 
-->

<!DOCTYPE html>

<html lang="en">
    <head>

        <meta charset="UTF-8">

        <!-- Responsive Web Design -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- HTML Page Description for SEO -->
        <meta name="description" content="Main landing page for MelonBall, a game development company specializing in tropical, relaxing, immersive games.">

        <!-- Keywords for SEO -->
        <meta name="keywords" content="Melonball, tropical, relaxing, immersive, games">

        <!-- Author Information -->
        <meta name="author" content="Jonah, James, Kia and Duc">

        <!-- Link to external CSS File -->
        <link rel="stylesheet" href="styles/stylessheet.css">

        <!-- Title of Web Page-->
        <title>MelonBall - Play Easy. Drift Far.</title>
        <!-- Embedded CSS for right panel text styling -->
        <style>
          .index_rightpanel h2 {
            color: #ffffff;
          }

          .index_rightpanel p {
            color: #ffffff;
            font-weight: lighter;
          }

          .index_rightpanel a {
            color: #ffffff;
            text-decoration: none;
          }

          .index_rightpanel a:hover {
            text-decoration: underline;
            text-decoration-color: rgb(103, 147, 161);
          }
        </style>
    </head>
    <body>
        <!-- php Header with navigation menu-->
        <?php include 'header.inc'; ?>
        
        <main>
        <!--Container for Flexbox that contains nested containers for left and right panel-->
          <div class="index_container">  
            <!--Left Panel with Logo, Company Name and Slogan-->
            <div class="index_leftpanel">
              <div class="index_text-overlay">
                <img id="white_logo" src="images/Logo_White.svg" alt="This is a white outlined version of MELONBALL's Logo against
                a cloudy rainforest" class="index_logo" title="Light MELONBALL Logo">
                <h1><strong>MELONBALL</strong></h1>
                <h2><em>Play Easy. Drift Far.</em></h2>
              </div>
            </div> 
            <!--Text Generated By ChatGPT-->
            <!--Right Panel with accessibility label. Contains info about company-->
            <div class="index_rightpanel" aria-labelledby="Introduction">
              <section id="Introduction">
              <!--Company Description with inline styling for MELONBALL-->
                <h2>Welcome to <strong style="color: #E0F0F0;">MELONBALL</strong> — where the tropics meet tranquility.</h2>
                  <p>
                      At MELONBALL, we’re passionate about creating video game experiences 
                      that go beyond entertainment. We specialize in tropical-inspired, 
                      immersive worlds that offer players a chance to relax, explore, and 
                      escape. Our mission is simple: craft games that feel like a 
                      vacation, whether you have five minutes or five hours to play.
                  </p>
                <h2>Why Tropical? Why Relaxing?</h2>
                  <p>
                      Every MELONBALL game is a love letter to warm breezes, ocean waves,
                      and the calming rhythm of island life. From lush jungles and quiet 
                      coves to sun-drenched villages and floating archipelagos, our worlds
                      are built to soothe your senses and spark your imagination. Gameplay 
                      is intuitive, peaceful, and player-driven — focusing on exploration,
                      creativity, and emotional connection rather than high-stress mechanics.
                  </p>  
                <h2>Games as Self-Care</h2>
                  <p>
                      We believe games can be a form of self-care. That’s why our titles are 
                      designed to be approachable, visually uplifting, and easy to fall into — 
                      whether you're a seasoned gamer or just looking for a peaceful digital 
                      escape after a long day.
                  </p>
                <!--anchor tag that the embedded CSS underlines. Takes to jobs.html-->
                <h2><a href="jobs.php"> Join us on This Journey</a></h2>
                  <p>
                      MELONBALL is more than a game studio. We're a team of artists, developers, 
                      and storytellers with a shared vision: to make games that bring joy, calm, 
                      and a sense of wonder. Our commitment to high-quality design and atmosphere 
                      ensures that every moment in a MelonBall game feels like a step away from the 
                      noise of everyday life.
                  </p>
              </section>
            </div>
          </div>
        </main>
        <!-- php Footer with links to Discord, Jira and email-->
        <?php include 'footer.inc'; ?>
    </body>
</html>